-- QUERY FUNCTIONS 

#1.
# Best and worst selling items: identify the products that have the least and most number of units sold. 
# top selling products should be ordered more and least selling products should be reviewed 
(SELECT 
    top_products.Product_Name AS Product,
    top_products.Units_Sold AS Units_Sold,
    'Top' AS Category
FROM
    (SELECT PName AS Product_Name, SUM(order_quantity) AS Units_Sold 
    FROM order_item o  
    INNER JOIN product p ON o.Pid = p.Pid  
    GROUP BY p.Pid, p.PName 
    ORDER BY Units_Sold DESC 
    LIMIT 2) AS top_products)
    
UNION 

(SELECT 
    bottom_products.Product_Name AS Product,
    bottom_products.Units_Sold AS Units_Sold,
    'Bottom' AS Category
FROM
    (SELECT PName AS Product_Name, SUM(order_quantity) AS Units_Sold 
    FROM order_item o  
    INNER JOIN product p ON o.Pid = p.Pid  
    GROUP BY p.Pid, p.PName 
    ORDER BY Units_Sold ASC 
    LIMIT 2) AS bottom_products);


#2.  
# Find which warehouses do the most shipping and how many employees this warehouse has 
# This count this will be useful to determine the most important warehouses and help allocation of manpower 
SELECT we.Wid,
       COUNT(we.Weid) AS employee_count,
       COALESCE(MAX(total_shipments), 0) AS total_shipments
FROM warehouse_employee we
LEFT JOIN (
    SELECT Wid, COUNT(Tid) AS total_shipments
    FROM delivery
    GROUP BY Wid
) AS shipment_counts ON we.Wid = shipment_counts.Wid
GROUP BY we.Wid
ORDER BY employee_count DESC, total_shipments DESC
LIMIT 3;


#3.
#Find which employee interacts with most customers. 
#This will help determine employee of the month who can get certain rewards. 
SELECT Ename, Ceid, COUNT(*) as total_interactions
FROM customer_call cc
INNER JOIN employee e ON e.Eid=cc.Ceid
GROUP BY Ceid
ORDER BY total_interactions DESC
LIMIT 1;

#4.
#Calculate customer lifetime value: how much revenue the customer has generated in their lifetime 
#Aggregate total revenue generated by each customer and find top customers
#These customers can be given some discounts to show appreciation and increase customer retention 

SELECT c.Cid, c.Cname, SUM(Oprice * order_quantity) as Total_Revenue FROM orders o
INNER JOIN order_item i ON o.Oid = i.Oid
INNER JOIN customer c ON c.Cid = o.Cid
GROUP BY c.Cid
ORDER BY total_revenue DESC
LIMIT 3;


#5. 
#Find which month has the most sales. This will identify consumer spending habits and help form strategies for discounts and deals
SELECT MONTHNAME(d.Sdate) AS Month_Name, SUM(o.Oprice * i.order_quantity) AS Total_Revenue 
FROM orders o
INNER JOIN order_item i ON o.Oid = i.Oid
INNER JOIN delivery d ON d.Tid = i.Tid
GROUP BY MONTHNAME(d.Sdate)
ORDER BY Total_Revenue DESC;


